### ISSUE TITLE
Optimize for Sysbox

### ISSUE THREAD

**Issue by felipecrs** [felipecrs/docker-images#61]
With Sysbox, there is no need for the dind hack.

**Comment by felipecrs** [comment]
Lines I can change when using Sysbox:

https://github.com/felipecrs/docker-images/blob/28a99ee42f4e38ea361317599f094a563f21dbd4/devcontainer/rootfs/etc/s6-overlay/s6-rc.d/dind/run#L7

```diff
- exec dind dockerd
+ exec dockerd
```

I can also probably remove these 2 files at initialization:

https://github.com/felipecrs/docker-images/blob/28a99ee42f4e38ea361317599f094a563f21dbd4/devcontainer/scripts/prepare_image.sh#L114-L115

With `rm -f /etc/subuid /etc/subgid` on entrypoint.sh.

**Comment by felipecrs** [comment]
@ctalledo, I was waiting to be able to run sysbox myself to verify whether sysbox-runc would inject any environment variable to make it easy for me to detect whether the container is running with sysbox or not, but there's no extra variable.

Do you have any idea on whether this can be accomplished? (without having to mount the docker socket and inspecting the container on host for the runtime).

**Comment by ctalledo** [comment]
Hi @felipecrs, 

> I was waiting to be able to run sysbox myself to verify whether sysbox-runc would inject any environment variable to make it easy for me to detect whether the container is running with sysbox or not, but there's no extra variable.

Yes I think in general we avoid inserting env variables into the container because we want it to resemble a clean Linux host environment as much as possible.

One easy way to detect if the container is running with Sysbox is to look for `sysboxfs` in the container mounts (e.g., `mount | grep sysboxfs`). Would this do or do you need a more formal method?

**Comment by felipecrs** [comment]
That's sufficient for sure. Thank you very much.
